[package]
name = "bcr-ebill-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false

[dependencies]
borsh.workspace = true
borsh-derive.workspace = true
async-trait.workspace = true
serde_json.workspace = true
serde.workspace = true
serde_repr.workspace = true
log.workspace = true
anyhow.workspace = true
thiserror.workspace = true
uuid.workspace = true
bitcoin.workspace = true
miniscript.workspace = true
nostr.workspace = true
futures.workspace = true
infer = { version = "0.22.0", default-features = false }
bcr-ebill-core.workspace = true
bcr-ebill-persistence.workspace = true
bcr-common.workspace = true
tokio.workspace = true
tokio_with_wasm.workspace = true
rand = { version = "0.10" }
strum.workspace = true
hex = { version = "0.4" }
url.workspace = true
base64.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwest = { workspace = true, features = ["json"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = { workspace = true, features = ["default", "json"] }

[dev-dependencies]
mockall.workspace = true
tokio.workspace = true
mockito.workspace = true
